package lmr.randomizer.rcd.object;

public final class ObjectIdConstants {
    public static final short Pot = 0x00;
    public static final short Enemy_Antlion = 0x01; // Myrmecoleon
    public static final short Enemy_Bat = 0x02;
    public static final short Enemy_Skeleton = 0x03;
    public static final short TogSpawner = 0x04;
    public static final short Enemy_Snouter = 0x05; // Snout Leaper
    public static final short Enemy_KodamaRat = 0x06;
    public static final short Ladder = 0x07;
    public static final short Dais = 0x08;
    public static final short MovingRoomSpawner = 0x0a;
    public static final short FlagTimer = 0x0b;
    public static final short MovingPlatform = 0x0c;
    public static final short RoomSpawner = 0x0e;
    public static final short OneWayDoor = 0x0f;
    public static final short Spikes = 0x10;
    public static final short Crusher = 0x11;
    public static final short Hitbox = 0x12;
    public static final short LemezaDetector = 0x14;
    public static final short Enemy_Snake = 0x16; // Axe Head
    public static final short Enemy_Cockatrice = 0x17;
    public static final short Enemy_Condor = 0x18;
    public static final short Enemy_MirrorGhosts = 0x1b; // Soul
    public static final short Enemy_MaskedMan = 0x1c;
    public static final short Enemy_Nozuchi = 0x1d;
    public static final short Enemy_Fist = 0x1e; // Rock Hand
    public static final short GhostSpawner = 0x1f;
    public static final short GhostLord = 0x20;
    public static final short RedSkeleton = 0x21;
    public static final short Steam = 0x23;
    public static final short Enemy_Sonic = 0x26; // Hedge
    public static final short Enemy_CatBall = 0x27; // Cait Sith
    public static final short Enemy_Bennu = 0x28;
    public static final short Enemy_PharaohHead = 0x29;
    public static final short Buer = 0x2a;
    public static final short Sphinx = 0x2a;
    public static final short Chest = 0x2c;
    public static final short WeaponCover = 0x2d;
    public static final short Ankh = 0x2e;
    public static final short FloatingItem = 0x2f;
    public static final short Trapdoor = 0x30;
    public static final short PressurePlate = 0x32;
    public static final short CounterweightElevator = 0x33;
    public static final short Seal = 0x34;
    public static final short Enemy_Gyonin = 0x35;
    public static final short Enemy_Hippocamp = 0x37;
    public static final short Enemy_Kraken = 0x38;
    public static final short Enemy_WaterLeaper = 0x39;
    public static final short Nuckelavee = 0x3a;
    public static final short Enemy_ExplodeRock = 0x3b; // Killer Rock
    public static final short Enemy_Slime = 0x3c;
    public static final short LavaRock = 0x3d; // Lava Ball
    public static final short Enemy_Kakoujuu = 0x3e;
    public static final short Enemy_Mandrake = 0x41;
    public static final short Enemy_Naga = 0x42;
    public static final short Enemy_Garuda = 0x43;
    public static final short Enemy_Blob = 0x44;
    public static final short Hekatonkheires = 0x45;
    public static final short Spriggan = 0x46;
    public static final short Enemy_Bonnacon = 0x48;
    public static final short Enemy_FlowerFacedSnouter = 0x49; // Miraculous Flower-faced Snouter
    public static final short Enemy_Monocoli = 0x4a;
    public static final short Enemy_JiangShi = 0x4b;
    public static final short Enemy_RongXuanwangCorpse = 0x4c;
    public static final short Enemy_Hundun = 0x4f;
    public static final short Enemy_Pan = 0x50;
    public static final short Enemy_Hanuman = 0x51;
    public static final short Enemy_Enkidu = 0x52;
    public static final short Enemy_Marchosias = 0x53;
    public static final short Enemy_Witch = 0x55;
    public static final short Enemy_Siren = 0x56;
    public static final short Enemy_XingTian = 0x57;
    public static final short Enemy_ZaoChi = 0x58;
    public static final short Enemy_Leucrotta = 0x59;
    public static final short Enemy_LizardMan = 0x5c;
    public static final short Enemy_Asp = 0x5d;
    public static final short Enemy_Kui = 0x5e;
    public static final short ChiYou = 0x61;
    public static final short Enemy_Toujin = 0x62;
    public static final short Enemy_DiJiang = 0x63;
    public static final short Enemy_IceWizard = 0x64; // Cailleach
    public static final short Enemy_Keseran = 0x65; // Fluffball
    public static final short Enemy_BaiZe = 0x66;
    public static final short Enemy_Anubis = 0x68;
    public static final short Enemy_Yowie = 0x69;
    public static final short Enemy_Troll = 0x6a;
    public static final short Anubis = 0x6b;
    public static final short NinjaSpawner = 0x6c;
    public static final short Enemy_ABaoAQu = 0x6d;
    public static final short Enemy_Andras = 0x6e;
    public static final short ChonchonSpawner = 0x6f;
    public static final short Enemy_Cyclops = 0x70;
    public static final short Vimana = 0x71;
    public static final short Enemy_BlackDog = 0x73;
    public static final short Enemy_Salamander = 0x74;
    public static final short MudManSpawner = 0x7c;
    public static final short Enemy_SwordBird = 0x7d; // Camio
    public static final short Enemy_Elephant = 0x7e; // Behemoth
    public static final short Enemy_Amon = 0x81;
    public static final short Enemy_Satan = 0x82; // Dimensional - Devil Crown Skull
    public static final short Enemy_Devil = 0x83; // Dimensional - Gargoyle / Satan / Telephone Demon
    public static final short UmuDabrutu = 0x84;
    public static final short Urmahlullu = 0x85;
    public static final short Kuusarikku = 0x87;
    public static final short Girtablilu = 0x88;
    public static final short Mushnahhu = 0x8a;
    public static final short Ushum = 0x8d;
    public static final short Mushussu = 0x8e;
    public static final short Enemy_MiniBoss = 0x8f;
    public static final short TheBoss = 0x90;
    public static final short FairyPoint = 0x91;
    public static final short Fog = 0x92;
    public static final short GraphicsTextureDraw = 0x93;
    public static final short EyeOfRetribution = 0x95;
    public static final short ExtendableSpikes = 0x96;
    public static final short WarpPortal = 0x97;
    public static final short WarpDoor = 0x98;
    public static final short FallingRoom = 0x9a;
    public static final short SoundEffect = 0x9b;
    public static final short UseItemDetector = 0x9c;
    public static final short Scannable = 0x9e;
    public static final short Autosave = 0x9f;
    public static final short ConversationDoor = 0xa0;
    public static final short Statue = 0xa2;
    public static final short Animation = 0xa3;
    public static final short KeyFairySpot = 0xa7;
    public static final short PushableBlock = 0xa9;
    public static final short BlockButton = 0xaa;
    public static final short LaserWall = 0xab;
    public static final short HotSpring = 0xad;
    public static final short Explosion = 0xb4;
    public static final short ItemGive = 0xb5;
    public static final short SavePoint = 0xb6;
    public static final short GrailToggle = 0xb7;
    public static final short XelpudPillar = 0xbb;
    public static final short MotherAnkh = 0xc0;
    public static final short MantraDetector = 0xc2;
    public static final short SnapshotsScan = 0xc3;
    public static final short TransitionGate = 0xc4;
    public static final short EscapeTimer = 0xc5;
    public static final short EscapeScreenShake = 0xc7;

    private ObjectIdConstants() { }
}