package lmr.randomizer.util;

public final class BlockConstants {
    public static final int ItemNameBlock = 1;
    public static final int ItemDescriptionBlock = 2;
    public static final int MenuBlock = 4;
    public static final int SoftwareBlock = 5;
    public static final int GrailPointBlock = 7;
    public static final int HTMapNamesLimitedBlock = 28;
    public static final int FootOfFuto = 88;
    public static final int FairyQueenFirstConversation = 215;
    public static final int FairyQueenWhenTheTimeComesConversation = 218;
    public static final int XelpudTalismanConversation = 369;
    public static final int XelpudPillarConversation = 370;
    public static final int MulbrukStoneConversationBlock = 392; // 0x188; stays with Mulbruk seal door
    public static final int MulbrukWakingUpConversationBlock = 393; // 0x189; moved to flag check conversations in randomizer
    public static final int MulbrukIntroBlock = 393; // Replaced for Helloween 2019
    public static final int MulbrukHTConversationBlock = 414; // 0x19e; Replaced for Halloween 2021

    public static final int ItemConversationMekuri = 37;
    public static final int ItemConversationPepper = 245;
    public static final int ItemConversationAnchor = 247;
    public static final int ItemConversationMiniDoll = 249;
    public static final int ItemConversationXmailer = 364;
    public static final int ItemConversationMulanaTalisman = 371;
    public static final int ItemConversationBookOfTheDead = 397;
    public static final int ItemConversationMapSurface = 716;
    public static final int ItemConversationProvocativeBathingSuit = 1012;

    public static final int Master_Hiner = 671; // Hiner - Surface NPC, 01-00-02
    public static final int Master_Moger = 672; // Moger - Surface NPC, 01-02-00
    public static final int Master_FormerMekuriMaster_Mekuri = 673; // Former Mekuri Master - Surface NPC, 01-07-00
    public static final int Master_PriestZarnac = 674; // Priest Zarnac - Guidance NPC, 00-04-01
    public static final int Master_PriestXanado = 675; // Priest Xanado - Mausoleum NPC, 02-02-00
    public static final int Master_PhilosopherGiltoriyo = 677; // Philosopher Giltoriyo - Spring NPC, 04-00-01
    public static final int Master_PriestHidlyda = 678; // Priest Hidlyda - Spring NPC, 04-06-01
    public static final int Master_PriestRomancis = 679; // Priest Romancis - Inferno NPC, 05-03-02
    public static final int Master_PriestAramo = 680; // Priest Aramo - Extinction NPC, 06-06-00
    public static final int Master_PriestTriton = 681; // Priest Triton - Extinction NPC, 06-09-01
    public static final int Master_PriestJaguarfiv = 683; // Priest Jaguarfiv - Twin Labs NPC, 07-10-01
    public static final int Master_FairyQueen_RequestPendant = 684; // The Fairy Queen - Endless NPC, 08-01-00
    public static final short Master_FairyQueen_WaitingForPendant = 685; // The Fairy Queen - Endless NPC, 08-01-00
    public static final int Master_FairyQueen_UnlockFairies = 686; // The Fairy Queen - Endless NPC, 08-01-00
    public static final short Master_FairyQueen_WhenTheTimeComes = 687; // The Fairy Queen - Endless NPC, 08-01-00
    public static final short Master_FairyQueen_TrueShrine1 = 688; // The Fairy Queen - Endless NPC, 08-01-00
    public static final int Master_MrSlushfund_Pepper = 689; // Mr. Slushfund - Illusion NPC, 10-08-00 - References ItemConversationPepper
    public static final short Master_MrSlushfund_WaitingForTreasures = 690;
    public static final int Master_MrSlushfund_Anchor = 691; // References ItemConversationAnchor
    public static final int Master_MrSlushfund_NeverComeBack = 692;
    public static final int Master_PriestAlest = 693; // Priest Alest - Illusion NPC, 10-08-01
    public static final int Master_StrayFairy = 694; // Stray fairy - Illusion NPC, 10-00-01
    public static final int Master_GiantThexde = 696; // Giant Thexde - Graveyard NPC, 11-07-00
    public static final int Master_PhilosopherAlsedana = 698; // Philosopher Alsedana - Moonlight NPC, 12-06-00
    public static final int Master_PhilosopherSamaranta = 700; // Philosopher Samaranta - Goddess NPC, 13-05-01
    public static final int Master_PriestLaydoc = 701; // Priest Laydoc - Ruin NPC, 14-00-01
    public static final int Master_PriestAshgine = 702; // Priest Ashgine - Birth NPC, 16-01-00
    public static final int Master_PhilosopherFobos_Ladder = 704;
    public static final int Master_PhilosopherFobos_MedicineCheck = 705; // Philosopher Fobos - Dimensional NPC, 17-02-00
    public static final int Master_8BitElder = 706; // 8bit Elder - Gate of Time NPC, 21-00-00
    public static final int Master_duplex = 707; // duplex - Illusion NPC, 10-02-02
    public static final int Master_Samieru = 708; // Samieru - Moonlight NPC, 12-03-00
    public static final int Master_Naramura = 709; // Naramura - Goddess NPC, 13-06-03
    public static final int Master_8BitFairy = 710; // 8bit Fairy - Gate of Time NPC, 20-00-01
    public static final int Master_PriestMadomono = 718; // Priest Madomono - Sun NPC, 03-04-02
    public static final int Master_PriestGailious = 723; // Priest Gailious - Inferno NPC, 05-02-01
    public static final short Master_Mulbruk_StoneConversation = 912; // 0x390; Mulbruk, Sun NPC, 03-03-00
    public static final short Master_PriestAlest_NoItem = 915;
    public static final int Master_MulbrukEscapeRegular = 924; // 0x39c
    public static final int Master_MulbrukEscapeSwimsuit = 926; // 0x39e
    public static final short Master_FairyQueen_TrueShrine2 = 985; // The Fairy Queen - Endless NPC, 08-01-00
    public static final int Master_Mulbruk_ProvocativeBathingSuitReaction = 1013;

    public static final int Master_Dracuet_WaitForNightfall = 726; // Tailor Dracuet - Guidance NPC, 00-06-00
    public static final int Master_Dracuet_BackInTime = 991; // Tailor Dracuet - Illusion NPC, 10-07-00
    public static final int Master_Dracuet_HugeCasket = 993; // Tailor Dracuet - Gate of Time NPC, 20-03-01
    public static final int Master_Fairy_NightSurface = 998; // Fairy - Night Surface NPC, 22-07-00
    public static final int Master_Dracuet_HTUnlocked = 1000; // Tailor Dracuet - Goddess NPC, 13-01-00
    public static final int Master_Dracuet_ProvocativeBathingSuit = 1011; // References ItemConversationProvocativeBathingSuit

    public static final int MultiMaster_ElderXelpudRandomSetA = 484; // Elder Xelpud - Surface NPC, 01-02-01
    public static final int MultiMaster_MulbrukRandomSetA = 485; // Mulbruk, Sun NPC, 03-03-00
    public static final int MultiMaster_Mulbruk_Awake = 990; // Mulbruk, Sun NPC, 03-03-00
    public static final int MultiMaster_ElderXelpudRandomSetC_Rug = 1019;
    public static final int MultiMaster_ElderXelpudRandomSetB = 1080;
    public static final int MultiMaster_ElderXelpudRandomSetC_NoRug = 1081;
    public static final int MultiMaster_MulbrukRandomSetB = 1082;
    public static final int MultiMaster_MulbrukRandomSetC = 1083;

    public static final int Sprite_Xelpud = 732; // Includes Xelpud bunemon info
    public static final int Sprite_Mulbruk = 736; // Includes Mulbruk bunemon info

    public static final int ShopBlockNebur = 34;
    public static final int ShopBlockNeburAlt = 490;
    public static final int ShopBlockSidro = 35;
    public static final int ShopBlockModro = 36;
    public static final int ShopBlockPenadventOfGhost = 39;
    public static final int ShopBlockGreedyCharlie = 74;
    public static final int ShopBlockShalomIII = 100;
    public static final int ShopBlockUsasVI = 102;
    public static final int ShopBlockKingvalleyI = 103;
    public static final int ShopBlockMrFishman = 132;
    public static final int ShopBlockMrFishmanAlt = 133;
    public static final int ShopBlockOperatorCombaker = 167;
    public static final int ShopBlockYiegahKungfu = 185;
    public static final int ShopBlockArrogantMetagear = 187;
    public static final int ShopBlockArrogantSturdySnake = 204;
    public static final int ShopBlockYiearKungfu = 205;
    public static final int ShopBlockAffectedKnimare = 220;
    public static final int ShopBlockMoverAthleland = 244;
    public static final int ShopBlockGiantMopiran = 272;
    public static final int ShopBlockGiantMopiranAngelShield = 273;
    public static final int ShopBlockKingvalleyII = 290; // Kingvalley II - Moonlight NPC, 12-07-00
    public static final int ShopBlockEnergeticBelmont = 303;
    public static final int ShopBlockMechanicalEfspi = 321;
    public static final int ShopBlockMudManQubert = 337; // Priest Ashgine - Birth NPC, 16-01-01
    public static final int ShopBlockHotbloodedNemesistwo = 470;
    public static final int ShopBlockTailorDracuet = 1008; // Tailor Dracuet - HT NPC, 23-08-01

    public static final int XelpudFlagCheckBlock = 480;
    public static final int XelpudScoreCheckBlock = 482;
    public static final int MulbrukFlagCheckBlock = 486;
    public static final int MulbrukScoreCheckBlock = 488;
    public static final int MulbrukRandomBlock1 = 489;
    public static final int MulbrukRandomBlock2 = 1078;
    public static final int MulbrukRandomBlock3 = 1079;

    public static final int Conversation_MulbrukEscapeRegular = 925;
    public static final int Conversation_MulbrukEscapeSwimsuit = 927;

    public static final int Removed_XelpudScoreWindHowling = 373;
    public static final int Removed_MulbrukLowScore = 719;
    public static final int Removed_MulbrukEmptyAfterProvocativeBathingSuit = 1014;
    public static final int Removed_WindHowlingSwimsuit = 1049;

    public static final int Email00 = 0x1ac;
    public static final int Email01 = 0x1ad;
    public static final int Email02 = 715;
    public static final int Email03 = 963;
    public static final int Email04 = 365;
    public static final int Email05 = 0x1ae;
    public static final int Email06 = 0x1af;
    public static final int Email07 = 0x1b0;
    public static final int Email08 = 0x1b1;
    public static final int Email09 = 0x1b2;
    public static final int Email10 = 0x1b3;
    public static final int Email11 = 0x1b4;
    public static final int Email12 = 0x1b5;
    public static final int Email13 = 0x1b6;
    public static final int Email14 = 0x1b7;
    public static final int Email15 = 0x1b8;
    public static final int Email16 = 0x1b9;
    public static final int Email17 = 0x1ba;
    public static final int Email18 = 0x1bb;
    public static final int Email19 = 0x1bc;
    public static final int Email20 = 0x1bd;
    public static final int Email21 = 0x1be;
    public static final int Email22 = 0x1bf;
    public static final int Email23 = 0x1c0;
    public static final int Email24 = 0x1c1;
    public static final int Email25 = 0x1c2;
    public static final int Email26 = 0x1c3;
    public static final int Email27 = 0x1c4;
    public static final int Email28 = 0x1c5;
    public static final int Email29 = 0x1c6;
    public static final int Email30 = 0x1c7;
    public static final int Email31 = 0x1c8;
    public static final int Email32 = 0x1c9;
    public static final int Email33 = 0x1ca;
    public static final int Email34 = 0x1cb;
    public static final int Email35 = 0x1cc;
    public static final int Email36 = 0x1cd;
    public static final int Email37 = 0x1ce;
    public static final int Email38 = 0x1cf;
    public static final int Email39 = 0x1d0;
    public static final int Email40 = 0x1d1;
    public static final int Email41 = 0x1d2;
    public static final int Email42 = 0x1d3;
    public static final int Email43 = 0x1d4;
    public static final int Email44 = 0x1d5;

    private BlockConstants() { }
}
