package lmr.randomizer;

public final class ItemConstants {
    public static final String WHIP = "Whip";
    public static final String CHAIN_WHIP = "Chain Whip";
    public static final String FLAIL_WHIP = "Flail Whip";
    public static final String KNIFE = "Knife";     // need to find and replace any grey named constant still
    public static final String KATANA = "Katana";
    public static final String AXE = "Axe";
    public static final String KEY_SWORD = "Key Sword";
    public static final String SHURIKEN = "Shuriken";
    public static final String ROLLING_SHURIKEN = "Rolling Shuriken";
    public static final String EARTH_SPEAR = "Earth Spear";
    public static final String FLARE_GUN = "Flare Gun";
    public static final String BOMB = "Bomb";
    public static final String CHAKRAM = "Chakram";
    public static final String CALTROPS = "Caltrops";
    public static final String PISTOL = "Pistol";
    public static final String BUCKLER = "Buckler";
    public static final String SILVER_SHIELD = "Silver Shield";
    public static final String FAKE_SILVER_SHIELD = "Fake Silver Shield";
    public static final String ANGEL_SHIELD = "Angel Shield";
    public static final String ANKH_JEWEL = "Ankh Jewel";
    public static final String ANKH_JEWEL_GATE_OF_GUIDANCE = "Ankh Jewel (Gate of Guidance)";
    public static final String ANKH_JEWEL_MAUSOLEUM_OF_THE_GIANTS = "Ankh Jewel (Mausoleum of the Giants)";     // the all_items.txt included these ankh jewels as separate, but seems like the code only distinguishes a few
    public static final String ANKH_JEWEL_TEMPLE_OF_THE_SUN = "Ankh Jewel (Temple of the Sun)";
    public static final String ANKH_JEWEL_SPRING_IN_THE_SKY = "Ankh Jewel (Spring in the Sky)";
    public static final String ANKH_JEWEL_TOWER_OF_RUIN = "Ankh Jewel (Tower of Ruin)";
    public static final String ANKH_JEWEL_CHAMBER_OF_BIRTH = "Ankh Jewel (Chamber of Birth)";
    public static final String ANKH_JEWEL_TWIN_LABYRINTHS = "Ankh Jewel (Twin Labyrinths)";
    public static final String ANKH_JEWEL_DIMENSIONAL_CORRIDOR = "Ankh Jewel (Dimensional Corridor)";
    public static final String ANKH_JEWEL_EXTRA = "Ankh Jewel (Extra)";
    public static final String HAND_SCANNER = "Hand Scanner";
    public static final String DJED_PILLAR = "Djed Pillar";
    public static final String MINI_DOLL = "Mini Doll";
    public static final String MAGATAMA_JEWEL = "Magatama Jewel";
    public static final String COG_OF_THE_SOUL = "Cog of the Soul";
    public static final String LAMP_OF_TIME = "Lamp of Time";
    public static final String POCHETTE_KEY = "Pochette Key";
    public static final String DRAGON_BONE = "Dragon Bone";
    public static final String CRYSTAL_SKULL = "Crystal Skull";
    public static final String VESSEL = "Vessel";
    public static final String PEPPER = "Pepper";
    public static final String WOMAN_STATUE = "Woman Statue";
    public static final String MATERNITY_STATUE = "Maternity Statue";
    public static final String KEY_OF_ETERNITY = "Key of Eternity";
    public static final String SERPENT_STAFF = "Serpent Staff";
    public static final String TALISMAN = "Talisman";
    public static final String DIARY = "Diary";
    public static final String MULANA_TALISMAN = "Mulana Talisman";
    public static final String MOBILE_SUPER_X2 = "Mobile Super X2";
    public static final String WATERPROOF_CASE = "Waterproof Case";
    public static final String HEATPROOF_CASE = "Heatproof Case";
    public static final String SHELL_HORN = "Shell Horn";
    public static final String GLOVE = "Glove";
    public static final String HOLY_GRAIL = "Holy Grail";
    public static final String ISIS_PENDANT = "Isis' Pendant";
    public static final String CRUCIFIX = "Crucifix";
    public static final String HELMET = "Helmet";
    public static final String GRAPPLE_CLAW = "Grapple Claw";
    public static final String BRONZE_MIRROR = "Bronze Mirror";
    public static final String EYE_OF_TRUTH = "Eye of Truth";
    public static final String RING = "Ring";
    public static final String SCALESPHERE = "Scalesphere";
    public static final String GAUNTLET = "Gauntlet";
    public static final String TREASURES = "Treasures";
    public static final String ANCHOR = "Anchor";
    public static final String PLANE_MODEL = "Plane Model";
    public static final String PHILOSOPHERS_OCARINA = "Philosophers' Ocarina";
    public static final String FEATHER = "Feather";
    public static final String BOOK_OF_THE_DEAD = "Book of the Dead";
    public static final String FAIRY_CLOTHES = "Fairy Clothes";
    public static final String SCRIPTURES = "Scriptures";
    public static final String HERMES_BOOTS = "Hermes' Boots";
    public static final String FRUIT_OF_EDEN = "Fruit of Eden";
    public static final String TWIN_STATUE = "Twin Statue";
    public static final String BRACELET = "Bracelet";
    public static final String PERFUME = "Perfume";
    public static final String SPAULDER = "Spaulder";
    public static final String DIMENSIONAL_KEY = "Dimensional Key";
    public static final String ICE_CAPE = "Ice Cape";   //May mess with the already defined trap constants? search for EXPLODING_CHEST_NAME to find those in Main.RandomizerUI


}